name: repository
on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  check:
    name: Protection checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 5
    env:
      HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      BASE_SHA: ${{ github.event.pull_request.base.sha }}

    steps:
      - name: Clone target branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch PR commits
        run: git fetch origin "${BASE_SHA}" "${HEAD_SHA}"

      - name: Check for node_modules availability and package.json consistency
        run: |
          # Make tools/node-modules available
          make pkg/lib/cockpit.js
          # for each commit in the PR which modifies package.json or node_modules...
          for commit in $(git log --reverse --full-history --format=%H \
                              "${HEAD_SHA}" --not "${BASE_SHA}" -- package.json node_modules); do
              # ... check that package.json and node_modules/.package.json are in sync
              tools/node-modules verify "${commit}"
          done
